### ISSUE TITLE
ufoJS

### ISSUE THREAD

**Issue by davelab6** [simoncozens/ufo.js#1]
Did you look at @graphicore 's ufoJS? :)

https://github.com/graphicore/ufoJS

**Comment by simoncozens** [comment]
I did. The idea here is an API-compatible drop-in replacement for opentype.js. I guess another way to do it would be an abstract umbrella interface to various different font libraries, but, well, I didn't do that.

**Comment by davelab6** [comment]
Thanks for explaining :)
